In [1]:
import numpy as np 

#create an original array
original_array = np.array([1,2,3,4,5,6])
print(original_array)

[1 2 3 4 5 6]


In [2]:
#create a view for the array
view_array = original_array.view()
print(view_array)

[1 2 3 4 5 6]


In [4]:
#modify a value within the view array
view_array[2]=30
print(view_array)
print("original array after modifuing the view: ", original_array)

[ 1  2 30  4  5  6]
original array after modifuing the view:  [ 1  2 30  4  5  6]


In [8]:
#create a copy of original array
copy_array = original_array.copy()
print(copy_array)

[ 1  2 30  4  5  6]


In [11]:
#modify element in copy array, change 1st element to 10
copy_array[0]=10
print(copy_array)

print("original array after copying the array: ", original_array)
#in original array no changes happen, because we edit in the copied array

[10  2 30  4  5  6]
original array after copying the array:  [ 1  2 30  4  5  6]
