In [5]:
import numpy as np

# Create an empty 3x4 NumPy array
empty_arr = np.empty((3, 4))
print(empty_arr)


[[6.23042070e-307 3.56043053e-307 1.60219306e-306 2.44763557e-307]
 [1.69119330e-306 1.78022342e-306 1.05700345e-307 3.11525958e-307]
 [1.69118108e-306 8.06632139e-308 1.20160711e-306 1.69119330e-306]]


In [2]:
import numpy as np

# Create a 3x4 NumPy array filled with the value 42
full_arr = np.full((3, 4), 42)
print(full_arr)


[[42 42 42 42]
 [42 42 42 42]
 [42 42 42 42]]
