In [4]:
import numpy as np

# Create two sample matrices
matrix_A = np.array([[1, 2, 3],
                     [4, 5, 6]])

matrix_B = np.array([[7, 8],
                     [9, 10],
                     [11, 12]])

# Perform matrix multiplication
result = np.matmul(matrix_A, matrix_B)

print("Matrix A:")
print(matrix_A)
print("Matrix B:")
print(matrix_B)
print("Result of matrix multiplication:")
print(result)


Matrix A:
[[1 2 3]
 [4 5 6]]
Matrix B:
[[ 7  8]
 [ 9 10]
 [11 12]]
Result of matrix multiplication:
[[ 58  64]
 [139 154]]
