In [1]:
import numpy as np

# Create two sample matrices
matrix_A = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])

matrix_B = np.array([[10, 11, 12],
                     [13, 14, 15],
                     [16, 17, 18]])

# Add the matrices
result_add = matrix_A + matrix_B

# Subtract the matrices
result_sub = matrix_A - matrix_B

print("Matrix A:")
print(matrix_A)
print("\nMatrix B:")
print(matrix_B)
print("\nResult of matrix addition:")
print(result_add)
print("\nResult of matrix subtraction:")
print(result_sub)


Matrix A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix B:
[[10 11 12]
 [13 14 15]
 [16 17 18]]

Result of matrix addition:
[[11 13 15]
 [17 19 21]
 [23 25 27]]

Result of matrix subtraction:
[[-9 -9 -9]
 [-9 -9 -9]
 [-9 -9 -9]]
